#!/bin/sh

set -e

failed() {
	if [ $? -ne 0 ]; then
		echo "Cancelled. Removing leftover files."
		rm  "$1"
	fi
}

bring_image(){
	trap 'failed nhos.img*' SIGINT
	wget "https://files.nicehash.com/nhminer/nhos/nhos-$NHOS_VERSION/image/nhos-$NHOS_VERSION.img.gz" -O "nhos.img.gz"
	gunzip "nhos.img.gz"
	return 0
}

shrink_image() {
	if [ "$(stat -c "%s" nhos.img)" -gt "$1" ]; then
		truncate nhos.img -s "$1"
		sgdisk -e nhos.img
	fi
}

convert_image(){
	trap 'failed nhos.vhd' SIGINT
	qemu-img convert nhos.img -O vpc -o subformat=fixed,force_size nhos.vhd
}

update_config(){

	if mount_image; then
		echo "Installing configuration..."
		cat << EOF > /mnt/configuration.txt
{
	"rig": {
		"btc": "$1",
		"worker": "",
		"group": ""
	},
	"access": {
		"ssh": {
			"key": "$2"
		}
	},
}
EOF
		umount /mnt
	else
		echo "Unable to mount. You need to mount the volume and edit the configuration manually."
	fi
}

mount_image(){
	if mknod /dev/loop128 b 7 128; then
		if partprobe /dev/loop128; then
			mount /dev/loop128p2 /mnt
		fi
	fi
}

if xxhsum --status -c nhos.vhd.sum ; then
	echo "VHD image exists already. I you want to recreate, delete the leftover images manually."
	exit 0
fi

sleep 10

if [ -n "$1" ]; then 
	BTC="$1"
fi

if [ -n "$2" ]; then
	SSH_KEY="$2"
fi

if [ -z "$BTC" ] || [ -z "$SSH_KEY" ]; then
	echo "You must provide your BTC address (NiceHash username) and an public SSH key."
	exit 1
fi

if [ -f nhos.img ]; then
	if [ ! -f nhos.vhd ]; then
	echo "Converting the RAW image to VHD..."
		shrink_image 702545408
		convert_image
	fi
else
	if [ ! -f nhos.img.gz ]; then
		echo "Downloading new image..."
		bring_image
	fi
	echo "Converting the RAW image to VHD..."
	shrink_image 702545408
	convert_image
fi

update_config "$BTC" "$SSH_KEY"

echo "Checksumming image..."
xxh128sum nhos.vhd > nhos.vhd.sum

echo "All done!"
